site_name: Quién tiene tus datos
site_url: https://socialtic.github.io/QTTD
site_description: Documentación del proyecto "Quién tiene tus datos"

nav:
  - 'Herramientas para analizar una app':
      - 'instalacion_laboratorio.md'
      - 'analisis_aplicaciones.md'
  - 'Plantila de aplicación': 'plantilla_app.md'
  - 'Aplicaciones analizadas':
      - 'Mi Pólicia': '2022-03/mi-policia.md'

theme:
  name: material
  language: es
  # logo: # logotipo del proyecto
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
plugins:
  - search:
      separator: '[\s\-\.\_]'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/socialtic
    - icon: fontawesome/brands/github
      link: https://github.com/socialtic/qttd
    - icon: material/web
      link: https://socialtic.org
